"""corpus-check: reconcile corpus.db against the legacy R index -> docs/CORPUS_CHECK.md."""
import csv
from collections import defaultdict

from .citations import uri_of
from .config import LEGACY, REPO
from .db import connect

TOLERANCE = 3


def corpus_check(log=print):
    con = connect()
    legacy = defaultdict(set)
    with open(LEGACY / "talks_rds_index.csv", newline="") as fh:
        for row in csv.DictReader(fh):
            legacy[row["date"][:7]].add(uri_of(row["href"]))
    ours = defaultdict(dict)  # conf -> uri -> (kind, title)
    for conf_id, uri, kind, title in con.execute("SELECT conf_id, uri, kind, title FROM talks"):
        ours[conf_id][uri] = (kind, title)

    lines = [
        "# Corpus check", "",
        "Generated by `python -m conference_analysis.insights corpus-check`. Compares the",
        "number of addresses per conference in `data/corpus.db` with the legacy R scrape",
        f"(`legacy/talks_rds_index.csv`, {sum(len(v) for v in legacy.values())} talks, "
        f"{min(legacy)} to {max(legacy)}).", "",
    ]
    totals = con.execute(
        "SELECT COUNT(DISTINCT conf_id), SUM(kind='address'), SUM(kind!='address'), "
        "SUM(CASE WHEN kind='address' THEN word_count END) FROM talks WHERE source='api'").fetchone()
    prov = con.execute("SELECT COUNT(*), SUM(word_count) FROM talks WHERE provisional=1").fetchone()
    para, notes, cites = (con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
                          for t in ("paragraphs", "footnotes", "citations"))
    lines += [
        f"- API conferences: {totals[0]} (1971-04 to 2026-04), {totals[1]} addresses "
        f"({totals[3]:,} words), {totals[2]} non-address items (sessions, sustainings, reports)",
        f"- Provisional talks (ldt-scribe, 2026-10): {prov[0]} ({prov[1]:,} words)",
        f"- Paragraphs: {para:,}; footnotes: {notes:,}; citations: {cites:,}", "",
        "| Conference | Addresses (API) | Legacy talks | Diff | Status |",
        "|---|---|---|---|---|",
    ]
    details, unexplained = [], 0
    for conf_id in sorted(c for c in ours if c in legacy or c <= max(legacy)):
        addresses = {u for u, (kind, _) in ours[conf_id].items() if kind == "address"}
        old = legacy.get(conf_id, set())
        diff = len(addresses) - len(old)
        if abs(diff) <= TOLERANCE:
            status = "ok"
        else:
            only_legacy = old - addresses
            only_api = addresses - old
            non_address = [u for u in only_legacy if u in ours[conf_id]]
            missing = [u for u in only_legacy if u not in ours[conf_id]]
            status = "explained below"
            details.append(f"### {conf_id} (diff {diff:+d})")
            if not old:
                details.append("- The legacy scrape has no rows for this conference.")
            if only_api:
                details.append(f"- {len(only_api)} addresses in the API that the legacy scrape "
                               "lacks: " + ", ".join(sorted(ours[conf_id][u][1] for u in only_api)[:12]))
            if non_address:
                details.append(f"- {len(non_address)} legacy rows are items we do not count as "
                               "addresses: " + ", ".join(
                                   f"{ours[conf_id][u][1]} ({ours[conf_id][u][0]})"
                                   for u in sorted(non_address)[:12]))
            if missing:
                unexplained += len(missing)
                details.append(f"- {len(missing)} legacy URLs are not in the API index at all: "
                               + ", ".join(sorted(missing)[:12]))
            details.append("")
        lines.append(f"| {conf_id} | {len(addresses)} | {len(old)} | {diff:+d} | {status} |")
    later = sorted(c for c in ours if c > max(legacy))
    lines += ["", f"Conferences after the legacy scrape ends ({', '.join(later)}) have no "
              "legacy counterpart.", "", "## Differences larger than ±3", ""]
    lines += details or ["None."]
    out = REPO / "docs" / "CORPUS_CHECK.md"
    out.write_text("\n".join(lines) + "\n")
    log(f"wrote {out} ({len(details)} detail lines, {unexplained} legacy URLs not in the API)")
